# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           displayconfig-mutter
Version:        0.1.4
Release:        %autorelease
Summary:        Change Gnome display settings from cli
License:        MIT
URL:            https://github.com/eaglesemanation/displayconfig-mutter
Source0:        https://github.com/eaglesemanation/displayconfig-mutter/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%description
xrandr like app for Gnome DE in Wayland mode. Allows modifying most parameters that are exposed in "Displays" settings.

%prep
%autosetup -n displayconfig-mutter-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/displayconfig-mutter

%changelog
%autochangelog
