on: push
name: Lint Rust

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo --locked fmt --all --check
      - run: cargo --locked check
      - run: cargo --locked clippy --all-targets --all-features -- -D warnings
      - run: cargo --locked test
      - run: cargo --locked build --release
