name: Publish release packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version number"
        required: true
        type: string

jobs:
  validate-and-patch:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.release_version }}
    permissions:
      contents: write
    steps:
      - name: Validate user input
        id: release_version
        run: |
          VERSION=${{ inputs.version }}
          (echo $VERSION | grep -Eq '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$') || echo '::error title=Invalid version::Workflow expects version input to be in form of "v{major}.{minor}.{patch}"'
          echo "release_version=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test
      - run: cargo build --release

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-bump
      - name: Update Cargo.toml version
        run: |
          cargo bump ${{ steps.release_version.outputs.release_version }}
      - name: Update PKGBUILD version 
        run: |
          sed -i -E "s/^(pkgver=).*/\1${{ steps.release_version.outputs.release_version }}/" dist/arch/PKGBUILD
      - name: Update RPM spec version
        run: |
          sed -i -E "s/^(Version:\W+).*/\1${{ steps.release_version.outputs.release_version }}/" dist/rpm/fedora.spec

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update release files to v${{ needs.build.outputs.release_version }}
      - uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: v${{ steps.release_version.outputs.release_version }}
          generateReleaseNotes: true
          makeLatest: true

  publish-aur:
    runs-on: ubuntu-latest
    needs: validate-and-patch
    steps:
      - uses: actions/checkout@v4
      - name: Build SRCINFO
        uses: heyhusen/archlinux-package-action@v2
        with:
          path: dist/arch
          srcinfo: true
          updpkgsums: true
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.AUR_KNOWN_HOSTS }}
      - name: Clone AUR repo
        run: git -c init.defaultBranch=master clone ssh://aur@aur.archlinux.org/displayconfig-mutter.git aur-displayconfig-mutter
      - name: Update PKGBUILD and SRCINFO in AUR repo
        run: |
          cp dist/aur/PKGBUILD dist/aur/.SRCINFO aur-displayconfig-mutter/
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: aur-repo
          commit_message: Release v${{ needs.build.outputs.release_version }}

